global:
  scrape_interval: 15s
rule_files:
  - 'alerts.yml'
scrape_configs:
  - job_name: 'fastapi-app1'
    static_configs:
      - targets: ['fastapi-app1-container:8000']
  - job_name: 'fastapi-app2'
    static_configs:
      - targets: ['fastapi-app2-container:8000']
  - job_name: 'order-processor'
    static_configs:
      - targets: ['order-processor-container:8000']
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'redis'
    static_configs:
      - targets: [ 'redis-exporter:9121' ]
  - job_name: 'postgresql'
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]
  - job_name: 'rabbitmq'
    static_configs:
      - targets: [ 'rabbitmq-container:15692' ]
    metrics_path: '/metrics'